version: "3.7"

services: # 하나로 묶어주는 서비스를 만듬
  nginx:    # nginx 컨테이너 부분
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_4ban_network

    volumes:
      - /home/wjekdns019/nginx.conf:/etc/nginx/nginx.conf
      - gis_4ban_static:/data/static/
      - gis_4ban_media:/data/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_4ban_network
    volumes:
      - gis_mariadb:/var/lib/mysql    # 마리아 db 사이트 에서 찾기 https://hub.docker.com/_/mariadb
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234
      # 마리아디비 env 는 메인파일 - settings - deploy

  django:   # django 부분
    image: gis_4ban_django:3
    networks:
      - gis_4ban_network

    volumes:
      - gis_4ban_static:/home/goHome-first-/staticfiles/
      - gis_4ban_media:/home/goHome-first-/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD


# 네트워크 생성
networks:
  gis_4ban_network:

# 볼륨 설정
volumes:
  gis_4ban_static:
  gis_4ban_media:
  gis_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true